[package]
name = "nushell-web-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
# dependencies for web development
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0", features = ["csr"] }

# nu
nu-cmd-extra = { version = "0.100.0", default-features = false }
nu-cmd-lang = { version = "0.100.0", default-features = false }
nu-command = { version = "0.100.0", default-features = false }
nu-engine = { version = "0.100.0", default-features = false }
nu-parser = { version = "0.100.0", default-features = false }
nu-protocol = { version = "0.100.0", default-features = false }
nuon = { version = "0.100.0", default-features = false }

# general stuff
thiserror = "1"

[patch.crates-io]
nu-cmd-extra = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
nu-cmd-lang = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
nu-command = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
nu-engine = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
nu-parser = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
nu-protocol = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
nuon = { git = "https://github.com/nushell/nushell.git", rev = "3bafc9d354134e7c1058f22b9a4dd4e081e7c06f" }
