name: continuous-integration

on:
  push:
  
env:
  TARGET: wasm32-unknown-unknown

jobs:
  cargo:
    name: cargo-${{ matrix.job.name }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        job:
          - name: check
            command: cargo check --target $TARGET
            continue-on-error: true
          - name: build
            command: cargo build --target $TARGET
            continue-on-error: false
          - name: doc
            command: cargo doc --target $TARGET
            continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: $TARGET
          cache-key: ${{ hashFiles('**/package-lock.json') }}
          cache-directories: "node_modules"
      - run: npm ci --ignore-scripts
      - run: ${{ matrix.job.command }}
        continue-on-error: ${{ matrix.job.continue-on-error }}
